name: Run settings_update workflow

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  run-settings-update-worflow:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke settings update workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update repository settings
          token: ${{ secrets.REPO_SETTINGS_TOKEN }}


# Example output:
# 
# Run benc-uk/workflow-dispatch@v1
# with:
#   workflow: Update repository settings
#   token: ***
# ğŸƒ Workflow Dispatch Action v1.2.4
# ğŸ” Found workflow, id: 141876675, name: Update repository settings, path: .github/workflows/settings_update.yml
# ğŸš€ Calling GitHub API to dispatch workflow...
# ğŸ† API response status: 204

# Remeber to add the token to the repository secrets!!! REPO_SETTINGS_TOKEN
# Run benc-uk/workflow-dispatch@v1
# ğŸƒ Workflow Dispatch Action v1.2.4
# Error: Parameter token or opts.auth is required